# Generated by Django 3.0.8 on 2021-04-26 01:48

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20210426_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='country',
            field=django_countries.fields.CountryField(default='CL', max_length=2),
            preserve_default=False,
        ),
    ]
