# Generated by Django 3.0.8 on 2021-04-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_menu_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='slack_user',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
