# Generated by Django 3.0.8 on 2021-04-26 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_auto_20210426_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='meals.Menu'),
            preserve_default=False,
        ),
    ]
