# Generated by Django 3.0.8 on 2021-04-26 23:09

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_auto_20210426_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'permissions': [('can_list', 'Can list menus'), ('can_update', 'Can update menus'), ('can_delete', 'Can delete menus'), ('can_publish', 'Can publish menus')]},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'permissions': [('can_list', 'Can list menus'), ('can_update', 'Can update menus'), ('can_detail', 'Can view details of menus'), ('can_delete', 'Can delete menus'), ('can_publish', 'Can publish menus')]},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_list', 'Can list menus')]},
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='menu',
            name='state',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
