# Generated by Django 3.0.8 on 2021-04-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_auto_20210427_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
